GET http://127.0.0.1:8001

###
GET http://127.0.0.1:8001/distritos

###
GET http://127.0.0.1:8001/distritos/6

###
GET http://127.0.0.1:8001/autoridades

###
GET http://127.0.0.1:8001/autoridades/70

###
GET http://127.0.0.1:8001/autoridades/clave/trc-j5-fam

###
GET http://127.0.0.1:8001/materias

###
GET http://127.0.0.1:8001/materias/6

###
GET http://127.0.0.1:8001/materias_tipos_juicios?materia_id=6

###
GET http://127.0.0.1:8001/materias_tipos_juicios/216

###
GET http://127.0.0.1:8001/materias_tipos_juzgados?materia_id=7

###
GET http://127.0.0.1:8001/materias_tipos_juzgados/2

###
GET http://127.0.0.1:8001/abogados?nombre=rosalba

###
GET http://127.0.0.1:8001/abogados/8702

###
GET http://127.0.0.1:8001/peritos?distrito_id=6&nombre=perez

###
GET http://127.0.0.1:8001/peritos/165

###
GET http://127.0.0.1:8001/edictos?autoridad_id=60&ano=2020

###
GET http://127.0.0.1:8001/edictos/28800

###
GET http://127.0.0.1:8001/glosas?autoridad_id=77&ano=2018

###
GET http://127.0.0.1:8001/glosas/1314

###
GET http://127.0.0.1:8001/listas_de_acuerdos?autoridad_id=60&ano=2020

###
GET http://127.0.0.1:8001/listas_de_acuerdos?autoridad_id=60&fecha=2020-09-08

###
GET http://127.0.0.1:8001/listas_de_acuerdos/64691

### Aun no hay, entrega listado vacio
GET http://127.0.0.1:8001/listas_de_acuerdos_acuerdos?lista_de_acuerdo_id=64691

### Aun no hay, entrega 404 Not found
GET http://127.0.0.1:8001/listas_de_acuerdos_acuerdos/1

###
GET http://127.0.0.1:8001/sentencias?autoridad_id=77&ano=2018

###
GET http://127.0.0.1:8001/sentencias/48063

###
GET http://127.0.0.1:8001/ubicaciones_expedientes?autoridad_id=9

###
GET http://127.0.0.1:8001/ubicaciones_expedientes?autoridad_id=9&expediente=1007/2017

###
GET http://127.0.0.1:8001/ubicaciones_expedientes/22445
