@base_url = http://127.0.0.1:8001/v2

### Abogados
GET {{base_url}}/abogados

### Abogados GARZA
GET {{base_url}}/abogados
    ?nombre=garza

### Abogados desde 2010 y hasta 2012
GET {{base_url}}/abogados
    ?anio_desde=2010
    &anio_hasta=2012

### Abogados GARZA desde 2010 hasta 2012
GET {{base_url}}/abogados
    ?nombre=garza
    &anio_desde=2010
    &anio_hasta=2012

### Un abogado
GET {{base_url}}/abogados/13014
