@base_url = http://127.0.0.1:8001/v2

### REDAM DataTable de deudores
POST {{base_url}}/redams
content-type: application/json

{}

### REDAM DataTable de deudores
POST {{base_url}}/redams
content-type: application/json

{
    "draw": 1,
    "start": 20,
    "length": 10
}

### Distrito Monclova
GET {{base_url}}/distritos/2

### REDAM listado de deudores del Distrito de Monclova
POST {{base_url}}/redams
content-type: application/json

{
    "distrito_id": 2
}

### Autoridad detalle del J. 3ro Familiar de Monclova
GET {{base_url}}/autoridades/11

### REDAM listado de deudores del J. 3ro Familiar de Monclova
POST {{base_url}}/redams
content-type: application/json

{
    "autoridad_id": 11
}

### REDAM un deudor
GET {{base_url}}/redams/108
