@base_url = http://127.0.0.1:8001/v2

### Autoridad SLT-J2-MER
GET {{base_url}}/autoridades/clave/SLT-J2-MER

### Sentencias
GET {{base_url}}/sentencias

### Sentencias del SLT-J2-MER
GET {{base_url}}/sentencias?autoridad_id=40

### Sentencias del SLT-J2-MER del 2019
GET {{base_url}}/sentencias?autoridad_id=40&anio=2019

### Sentencia 22700
GET {{base_url}}/sentencias/22700
